### ISSUE TITLE
Unable to deploy this helm chart with falcosecurity/falco-no-driver:0.23.0

### ISSUE THREAD

**Issue by natchaphon-r** [falcosecurity/charts#17]
**Describe the bug**
Falco pods fail to start as the Falco binary is unable to locate a pre-installed BPF probe `/root/.falco/falco-bpf.o`.
```
Wed May 27 00:25:04 2020: Falco initialized with configuration file /etc/falco/falco.yaml
Wed May 27 00:25:04 2020: Loading rules from file /etc/falco/falco_rules.yaml:
Wed May 27 00:25:05 2020: Loading rules from file /etc/falco/falco_rules.local.yaml:
Wed May 27 00:25:06 2020: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Wed May 27 00:25:07 2020: Unable to load the driver. Exiting.
Wed May 27 00:25:07 2020: Runtime error: can't open BPF probe '/root/.falco/falco-bpf.o': Errno 2. Exiting.
```

**How to reproduce it**

Create a chart override file test.yaml:
```
image:
  registry: docker.io
  repository: falcosecurity/falco-no-driver
  tag: 0.23.0
  pullPolicy: IfNotPresent

ebpf:
  enabled: true

auditLog:
  enabled: true
  dynamicBackend:
    enabled: true
```

Run
`helm install falco -f falco/values.yaml -f test.yaml -n falco --generate-name`

Note that I pre-installed Falco BPF probe by using falco-driver-loader which by default installs BPF probe in /root/.falco 

`docker run --rm --privileged --name falco-probe-installer -v /root/.falco:/root/.falco -v /proc:/host/proc:ro -v /boot:/host/boot:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro -v /etc:/host/etc:ro --env FALCO_BPF_PROBE="" falcosecurity/falco-driver-loader:0.23.0`

**Expected behaviour**

The Falco chart should support deploying falcosecurity/falco-no-driver:0.23.0

**Screenshots**

**Environment**

- Falco version:
falcosecurity/falco-no-driver:0.23.0
- OS:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel:
`Linux ip-10-97-143-63 5.3.0-42-generic #34~18.04.1-Ubuntu SMP Fri Feb 28 13:42:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method:
falco-driver-loader

**Additional context**

- I was able to bypass this reported error by mounting /root to Falco pod.
- Should this chart support pre-installing Falco BPF probe/module by making use of falco-driver-loader as initContainer?

**Comment by leogr** [comment]
Hey @natchaphon-r 

Thanks for reporting this!

Currently, the helm chart has no support yet for this use case, and I agree it should be added.

I believe the initContainer approach (for example, as here https://github.com/helm/charts/pull/12343 ) makes sense, but we still need to implement the [least privileged method](https://github.com/falcosecurity/evolution/issues/25) in the right way. That's also important to make this use case working with both the available drivers (ie. the kernel module and the bpf probe).
Ofc, feel free to open a PR if you would like to work on this!

That being said, the approach of pre-installing the driver (and mounting `/root/.falco`) is still a valid workaround in case of the bpf probe (it won't work with the kernel module, because even if the kernel module was present in `/root/.falco`, the `falco-no-driver` is not able to insmod it).
Not sure if it is worth adding a configurable option for that in the chart.

**Comment by leogr** [comment]
This issue should be solved by https://github.com/falcosecurity/charts/tree/master/falco#using-an-init-container
