### ISSUE TITLE
k8s audit rule for GKE cluster

### ISSUE THREAD

**Issue by mkhodave** [falcosecurity/charts#248]
**How to enable k8s audit rules trigger for GKE cluster**

I would really like to see steps where I can enable k8s audit rule for GKE cluster
I set auditLog.enabled as true but whenever I do any changes in gke cluster , nothing reported at falco
Please guide

**Comment by Issif** [comment]
Hello @mkhodave, we managed k8s clusters like GKE, AKS or EKS, the audit are collected by the provider and we can't ask k8s to send them to falco. Since last release of falco (0.30.0), a plugin system for inputs has been integrated (beta): https://github.com/falcosecurity/plugins

We're working to integrate a plugin for EKS and I'm sure other providers will be added soon.
