### ISSUE TITLE
Add ingress support in the Falco chart

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/charts#375]
**Motivation**

Some Falco plugins require that Falco is reachable from outside the cluster (e.g. K8s audit).
Currently, the Falco chart only supports automatic service creation - ingress creation not. In the mentioned example in the `values.yaml` it's a [`NodePort` service](https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L142-L151) which is used for making Falco externally reachable, which may not be possible for everyone (e.g. we run VMware Tanzu (TKGI) with NSX-T (NCP CNI), which does not support services of type `NodePort`).
For that reason, a supported solution for a `CluserIP` & `Ingress` scenario setups would be nice.

**Feature**

- Add an `Ingress` template
- Add `ClusterIP` example to the `services` array inside `values.yaml`
- Add ingress config section to the `values.yaml`

**Alternatives**

Every user defines its own ingress object and applies it separately - not managed by Helm.

**Additional info**

If you agree that such a feature would be beneficial, I'll create a PR.

Regards,
Philip

**Comment by leogr** [comment]
Hey @PhilipSchmid 

I apologize for the very late reply, but I lost track of this issue. Sorry.

Although I understand the need, I'm not totally convinced that ingress creation should be a chart's responsibility.
In our original intent, one should be able to configure the ClusterIP in the chart and map to an Ingress created by other means.
In this way, we would allow a wide degree of freedom, considering the Ingress configuration may be drastically different depending on the plugin and the environment. 
Otherwise, the Ingress template in the chart should support all possible Ingress configurations, which is not trivial.

That being said, I may be totally wrong :sweat_smile: So, I'm open to any solution if we think it's reasonable.

cc
@falcosecurity/charts-maintainers @alacuku wdyt?

**Comment by PhilipSchmid** [comment]
Hi Leo,

Thanks for your valuable input. You are right. The maintenance of an ingress template could get quite tricky, as it needs to be very flexible regarding its configurations. Let's wait a bit and see, what others would think about that, and if there isn't a larger consent that it would be nice to have that, we simply close this issue with "won't fix/implement".

Regards,
Philip
