### ISSUE TITLE
Falco exporter does not work if we have Syscall + K8S plugin

### ISSUE THREAD

**Issue by afreyermuth98** [falcosecurity/charts#533]
I actually have inside my cluster 2 releases of falco :
- 1 that deploy a daemonset of falco on every node
- 1 other that deploy a unique replicaset of falco-k8saudit-eks plugin to analyze my EKS Cloudwatch logs

I've deployed falco-exporter to export some prometheus metrics to Grafana but this falco-exporter only export the data from the base falco or only from the k8s plugin falco so I always miss some informations.

The fact that we have a "double" falco install seems to fail inside falco-exporter

**Expected behaviour**
Deploy 1 daemonset of falco et 1 replicaset of falco k8s audit plugin.
Port forward the falco exporter pod which is on the same node as the falco k8saudit one.
See that you only have the k8saudit values or the base falco values.

Get the value of the base falco AND the k8saudit falco inside the falco-exporter on the same node to no miss data

**Environment**

- Falco version:

- System info: 3.6.2

- Cloud provider or hardware configuration: AWS
- OS: Ubuntu 22.04

- Installation method: Kubernetes (Helm)

**Additional context**

**Comment by alacuku** [comment]
Hi @afreyermuth98 `falco-exporter` can't handle multiple sources at once. It will connect to the available `unix:///run/falco/falco.sock` socket. In the node where there are two instances of falco only one of the `unix sockets` will be available since they later instance will overwrite the existing `unix socket`.

To make it work in your scenario, you will need to change the path where the falco `unix socket` is exposed and deploy a new instance for each k8s.

Anyway i think the best approach would be to deploy `falco-exporter` as a sidecar.

**Comment by alacuku** [comment]
You'll have as much falco-exporter as falco deployments. In your scenario you will have:

* falco with syscalls deployed as a deamonset + falco-exporter as daemonset configured to attach to the UNIX sockets exposed by the falco falco pods of the daemonset;
* falco with k8saudit deployed as a deployment + falco-exports as deployment contifured to attach to the UNIX sockets exposed by the falco pod of the deployment. Rempember that the falco pod and falco-exporter pod need to be run on the same node.

The best approach would be to deploy falco-exporter as a sidecar. Unfortunately the current charts does not support this configuration.

**Comment by afreyermuth98** [comment]
Yes I agree with you !
@alacuku Unfortunately, it seems that we cannot deploy falco-exporter as a deployment :'(
