### ISSUE TITLE
There is no way to install Falco in private network without internet using Helm

### ISSUE THREAD

**Issue by EsDmitrii** [falcosecurity/charts#544]
**Describe the bug**

Hi!
Is there any way to install Falco without internet in Kubernetes using Helm?
k8s cluster running in private network without internet, all images pulls via nexus proxy or via our private regestries.
I can't find any options to use proxy or private registry or something else to download binaries and modules from.
As workaround I can add default rules that Falco download via sidecar init container from GitHub using `customRules`. I copy the list of rules, and add them like this way:
```
customRules:
  default-rules.yaml: |-
     ***rules goes here***
```
I found that there are a lot of links to useful resources and plugins in index falcosecurity [here](https://falcosecurity.github.io/falcoctl/index.yaml)
In theory I can try to download all binaries to my private registry and replace links, but I think it should be more elegant way.

**How to reproduce it**

Try to install Falco to k8s without access to the Internet

**Screenshots**
<img width="1051" alt="Screenshot 2023-10-04 at 16 05 47" src="https://github.com/falcosecurity/charts/assets/124890665/486dd06e-a246-4788-9612-cbf9d46bcb29">

- Falco version: latest helm ver on 4 Oct 23
- Installation method: Kubernetes (Helm)

**Comment by LucaGuerra** [comment]
Hi @EsDmitrii , it is possible to achieve what you are mentioning in several ways:

1. Regarding the driver loader it appears that you are using kernel 3.x . The current image is a bit newer than that so it does not contain the necessary toolchain to compile the driver for those kernels. However, we distribute an older one as well that you can use with the chart https://github.com/falcosecurity/charts/tree/master/falco#selecting-an-different-driver-loader-image . Alternatively, you can distribute your kmod versions in your internal webserver and use the `DRIVER_REPO` env variable in the loader container to specify a different host than the default one so it won't connect to the Internet

3. Regarding the rules (and plugins!) you have a number of options. To name a few:
- Configmap: examples here -- https://falco.org/blog/rules-helm-chart-3-0-0/ basically that is ok if you want to quickly change the rules in your k8s cluster, but will probably not be the right solution if you want to mirror the official ones or you have a versioned rules repo that you are maintaining for your environment.
- Mirroring artifacts from the official Falco repositories: if you only need to mirror the official rules files you can simply copy them over or mirror them from https://github.com/orgs/falcosecurity/packages?repo_name=rules , for example if you copy `ghcr.io/falcosecurity/rules/falco-rules:2` (floating tag, or `2.0.0` full tag, or both!) onto `registry.internal.example.com/falcosecurity/rules/falco-rules:2` you will be able to install the helm chart with `helm install falco falcosecurity/falco --set "falcoctl.config.artifact.install.refs={registry.internal.example.com/falcosecurity/rules/falco-rules:2} --set "falcoctl.config.artifact.follow.refs={registry.internal.example.com/falcosecurity/rules/falco-rules:2}"` so that all downloads will point to your registry (usage of index files is required if you want signature check as well!)
- Full GitOps with OCI artifact distribution: you can publish and load own your rules onto any OCI registry, public or private, such as the one you use for distributing container images. This is an in-depth blog post that explains that in detail including the usage of the index files: https://falco.org/blog/gitops-your-falco-rules/

**Comment by EsDmitrii** [comment]
Hi @LucaGuerra !
Thank you for your help!
Will try these ways:)
I appreciate it!
