### ISSUE TITLE
Latest version (4.7.2) adds both 'rules_files' and 'rules_file' keys in /etc/falco/falco.yaml wich crashes the pods

### ISSUE THREAD

**Issue by JuanJTorres11** [falcosecurity/charts#728]
**Describe the bug**

I upgraded the helm chart with the latest version at the time (4.7.2). This caused the new pods to crash. Looking at the logs it says the following:

> Defaulted container "falco" out of: falco, falcoctl-artifact-follow, falco-driver-loader (init), falcoctl-artifact-install (init)
> Fri Aug  9 23:26:15 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
> Error: Error reading config file (/etc/falco/falco.yaml): both 'rules_files' and 'rules_file' keys set

**How to reproduce it**

I just used the following command on a cluster that already had falco running without problems 

`helm upgrade falco falcosecurity/falco --namespace falco -f values.yaml`

**Expected behaviour**

It should keep running properly.

**Screenshots**

**Environment**

- Falco version: 0.38.1

- System info: Linux version 5.15.0-1044-aws (buildd@lcy02-amd64-094) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34 {"default_driver_version":"7.2.0+driver","driver_api_version":"8.0.0","driver_schema_version":"2.0.0","engine_version":"40","engine_version_semver":"0.40.0","falco_version":"0.38.1","libs_version":"0.17.2","plugin_api_version":"3.6.0"}

- Cloud provider or hardware configuration: AWS EC2 
- OS: "Debian GNU/Linux 12 (bookworm)

- Kernel: Linux falco-thfmr 5.15.0-1044-aws

- Installation method:

Helm Chart

**Additional context**

**Comment by Kiliandeca** [comment]
Had the same problem, https://github.com/falcosecurity/charts/pull/720 renamed the default values `rules_file` to `rules_files` so if you had overridden `rules_file` your `values.yaml` you end up with the 2 keys in your config which make Falco throw an error [as expected](https://github.com/falcosecurity/falco/pull/3162/files#diff-9bd683a06f316f8dab7df7c882f9d1857df11de6ae476356e5f2f86068891157R273).

The fix is easy just rename `rules_file` to `rules_files` in your `values.yaml`. This should have been considered as a breaking change in the chart and not a simple fix.

**Comment by leogr** [comment]
> The fix is easy just rename `rules_file` to `rules_files` in your `values.yaml`. This should have been considered as a breaking change in the chart and not a simple fix.

@Kiliandeca :+1: and thanks for the explanation

@JuanJTorres11, can you confirm whether the above solution works for you?

**Comment by JuanJTorres11** [comment]
Sorry, I haven't seen the comment before. I just tried that and could successfully update to the latest version of the chart. Thanks @Kiliandeca 💚
